version: "3.9"

services:
  db:
    image: postgres:15
    container_name: turisticka_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: turisticka_agencija
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: turisticka_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./public/images:/app/public/images
    command: sh -c "sleep 5 && npx prisma generate && npx prisma migrate deploy && npm run start"

volumes:
  db_data: